name: Review Approved

on:
  pull_request_review:
    types:
      - submitted
  # 也可以添加手动触发功能
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  build-test:
    name: "Build and Test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - name: Install canvas dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
      - name: Install yarn
        run: npm install -g yarn
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Test build website
        run: yarn run build
  auto-merge:
    name: Auto Merge PR
    runs-on: ubuntu-latest
    needs: [build-test]
    if: needs.build-test.result == 'success'
    steps:
      - env:
          GH_TOKEN: ${{ secrets.MY_GIT_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        name: Auto merge PR
        run: gh pr merge --auto --merge "$PR_URL"
