name: Review Approved

on:
  pull_request_review:
    types:
      - submitted
  # 也可以添加手动触发功能
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  build-test:
    name: "Build and Test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - name: Install canvas dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Test build website
        run: pnpm run build
  auto-merge:
    name: Auto Merge PR
    runs-on: ubuntu-latest
    needs: [build-test]
    if: needs.build-test.result == 'success'
    steps:
      - name: Auto merge PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo, number: pull_number } = context.issue;
            try {
              await github.rest.pulls.merge({
                owner,
                repo,
                pull_number,
                merge_method: 'merge'
              });
              console.log(`Successfully merged PR #${pull_number}`);
            } catch (error) {
              console.error(`Failed to merge PR #${pull_number}:`, error);
            }
